//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALES_PROJECT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SALES_PROJECT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1000_F_179087574_aXjXMWEtMCpcB7hiOW7gjomzJKz4i1Y8 {
            get {
                object obj = ResourceManager.GetObject("1000_F_179087574_aXjXMWEtMCpcB7hiOW7gjomzJKz4i1Y8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1000_F_179087574_aXjXMWEtMCpcB7hiOW7gjomzJKz4i1Y81 {
            get {
                object obj = ResourceManager.GetObject("1000_F_179087574_aXjXMWEtMCpcB7hiOW7gjomzJKz4i1Y81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _240_F_366310107_VqBk8RzM8gn0xcGLcOxdU6rCt35TvRwH {
            get {
                object obj = ResourceManager.GetObject("240_F_366310107_VqBk8RzM8gn0xcGLcOxdU6rCt35TvRwH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _240_F_366310107_VqBk8RzM8gn0xcGLcOxdU6rCt35TvRwH1 {
            get {
                object obj = ResourceManager.GetObject("240_F_366310107_VqBk8RzM8gn0xcGLcOxdU6rCt35TvRwH1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _240_F_366310107_VqBk8RzM8gn0xcGLcOxdU6rCt35TvRwH2 {
            get {
                object obj = ResourceManager.GetObject("240_F_366310107_VqBk8RzM8gn0xcGLcOxdU6rCt35TvRwH2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _240_F_366310107_VqBk8RzM8gn0xcGLcOxdU6rCt35TvRwH3 {
            get {
                object obj = ResourceManager.GetObject("240_F_366310107_VqBk8RzM8gn0xcGLcOxdU6rCt35TvRwH3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _240_F_366310107_VqBk8RzM8gn0xcGLcOxdU6rCt35TvRwH4 {
            get {
                object obj = ResourceManager.GetObject("240_F_366310107_VqBk8RzM8gn0xcGLcOxdU6rCt35TvRwH4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _240_F_420158804_29BhddREdejn4sk3IaO2ZFW4JXMb0rbs {
            get {
                object obj = ResourceManager.GetObject("240_F_420158804_29BhddREdejn4sk3IaO2ZFW4JXMb0rbs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _240_F_420158804_29BhddREdejn4sk3IaO2ZFW4JXMb0rbs1 {
            get {
                object obj = ResourceManager.GetObject("240_F_420158804_29BhddREdejn4sk3IaO2ZFW4JXMb0rbs1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _240_F_420158804_29BhddREdejn4sk3IaO2ZFW4JXMb0rbs2 {
            get {
                object obj = ResourceManager.GetObject("240_F_420158804_29BhddREdejn4sk3IaO2ZFW4JXMb0rbs2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _240_F_420158804_29BhddREdejn4sk3IaO2ZFW4JXMb0rbs3 {
            get {
                object obj = ResourceManager.GetObject("240_F_420158804_29BhddREdejn4sk3IaO2ZFW4JXMb0rbs3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4882066 {
            get {
                object obj = ResourceManager.GetObject("4882066", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48820661 {
            get {
                object obj = ResourceManager.GetObject("48820661", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48820662 {
            get {
                object obj = ResourceManager.GetObject("48820662", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48820663 {
            get {
                object obj = ResourceManager.GetObject("48820663", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aerial_view_business_team {
            get {
                object obj = ResourceManager.GetObject("aerial-view-business-team", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_12859789_stock_photo_admin_tag {
            get {
                object obj = ResourceManager.GetObject("depositphotos_12859789-stock-photo-admin-tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap low_poly_banner_design_1711 {
            get {
                object obj = ResourceManager.GetObject("low_poly_banner_design_1711", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pexels_fauxels_3183198 {
            get {
                object obj = ResourceManager.GetObject("pexels-fauxels-3183198", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
